### PR TITLE
Russian Language Translation

### PR DESCRIPTION
**Pull request by netsafe**
Good daytime! I've made a translation for Russian language, and we are describing this project in russian crowdsoursing and crowdfunding online course at http://crowdcourse.net/ru/ssl-perspectives-project . It's in russian now, english version will be soon. Also I've added a notary we're running 24/7/365 at crowdcourse.net:8080 into default notary list. Looking forward to make this code better!

Cheers,
   Alexey Vesnin

### CODE REVIEW

**Comment by daveschaefer** [comment]
Hi @netsafe - thank you very much for the pull request and hard work! This is fantastic :)

I have some real-life commitments and won't be able to fully merge this request for at least one week. However, I will look into this ASAP. Please also note that there are some [outstanding issues](https://github.com/danwent/Perspectives/labels/blocks_amo_approval) that need to be fixed before I'll be able to fully update and include the new translation on addons.mozilla.org.

With that said I am *very* excited to have a Russian translation. Thank you very much!

**Comment by netsafe** [comment]
Hi @daveschaefer - I'll add russian manual page for regular users as soon as it will be ready! I'm continuing some fix-up's, but the one I've recently made is urgent : it prevents a P-button to be displayed in latest firefox version. I've fixed it and commited a patch. Also I've made a new compiled add-on available to the public at http://crowdcourse.net/sites/crowdcourse.net/files/Perspectives.xpi . It contains the translation and button appearance fix-up, verified to work.

**Comment by daveschaefer** [comment]
Hey, thanks, a translated manual sounds great. The documentation needs to be updated in general, but it is lower in priority than several other tasks first.

>prevents a P-button to be displayed in latest firefox version. I've fixed it and commited a patch.

Would you be willing to send a separate pull request with your fix?

**Comment by netsafe** [comment]
Sorry, GitHub does not permitting me to do this : I'm redirected to this one. Fixing issue with async DNS ;) So get ready for some patches

**Comment by netsafe** [comment]
Forgot to mention: issue 103 is already fixed also

**Comment by daveschaefer** [comment]
You may have to create a new branch before sending a separate pull request - e.g. [see here](http://stackoverflow.com/a/8450535/28037). Are you familiar with how to do that? If not just shout and we can walk you through it.

I really appreciate all of your work! Thanks. I'm afraid I still won't have time to review or merge pull requests until next week though.

**Comment by netsafe** [comment]
I'll try to use a CLI tool for next commit as specified on the link you've mentioned. Fixing DNS resolver - just minor bugs left.

**Comment by netsafe** [comment]
Sorry man, it seems to be not working with a separate branch. I'm new to Git, used SVN before, trying to learn Git. DNS resolver is working OK and fully asynchronously

**Comment by daveschaefer** [comment]
Hey, thanks for all of the work. No worries about figuring out git. What dev environment are you using? Do you prefer command line or a GUI?

At worst I can likely sync your branch to my machine and cherrypick the commits out before publishing them if we're unable to get branches working for you.

**Comment by daveschaefer** [comment]
For fixing the 'extensions.perspectives' prefix, the tricky part will be that we want to provide a way to upgrade people's existing preferences to the new prefix when they install a new version of the plugin. This could likely be code in the same place as the code for putting the Perspectives button on the toolbar when installing for the first time. We'll want to check and see if they have any of the old-style 'perspectives.x' preferences, and if so copy them over to 'extensions.perspectives' (and optionally, delete the old ones).

Given this, my preference would be to do one release that contains your Russian locialization to get that out right away, perhaps another release for the other fixes, and keep the pref moving changes in its own release. That would minimize the scope of testing and issues as people upgrade from one set of changes to the next.

**Comment by daveschaefer** [comment]
As for fixing the 'report attack' functionality - I have concerns about simply switching it back on. The receiving server should be using https to encrypt data before we start sending anything across the network. The server also had some stability issues so we'd want to make sure it worked first, And ideally the code for the receiving server would be public so everyone can at least see what we're doing (this is an open source project after all).

Again, getting the report server going is a separate issue from changing the synchronous code call. When you upload to addons.mozilla.org I believe they're simply grepping the code to see if the sync call is there - so if we delete that line and leave the reporting functionality commented out then it should work just fine.

**Comment by netsafe** [comment]
I'm using Ubuntu 14 CLI cloud image, kind of old-school :) All the old calls I left commented, so you can review the code easily, no sync DNS calls are used now. Because we're using report after loading page and notary checks, it's already in DNS cache, so what the exact problem they had with a sync call - I have no idea, but whatever. The preferences migration code can be inserted into init.js and I'll do it later tomorrow. This extension was veryfied in Windows 7, works fine.

**Comment by netsafe** [comment]
Preferences migration is done and tested to work correctly. Check it out :)

**Comment by netsafe** [comment]
I've started some refactoring in another branch, I'll make a pull request when it will be ready. The aim is to make a browser container interfaces "pluggable" :) So we will be able to make a Chrome version in a day or two - just by writing a browser interface wrapper. And also please add our notary to the list, please.

**Comment by daveschaefer** [comment]
The preferences migration code is beautiful! :) Thanks muchly.

Yes, getting all of the browser-specific calls moved into one place would be a very great thing to do.

We'll have to coordinate your refactoring branch with lambdor's refactoring work in the other open pull request. I have been away from Perspectives work for some time and it will be good to get it going again.

**Comment by daveschaefer** [comment]
Hey @netsafe - okay, the Russian localization looks good, and all of the data formatting passes even after testing it with the latest version of the checkloc script. Great work! :)

I'll work to package and publish a russian localization in the next week, and then integrate the patches for fixing AMO blocker. Then we'll see if we can find a nice way to merge your other changes in with @lambdor 's code from the other pull requests. Stay tuned!

**Comment by netsafe** [comment]
The version with AAMO-fixing patches is well-tested now : no bugs found, checked myself and with some volunteers. Please add our server to the the notary list, and we need to fix default ones : they are not working =(

**Comment by daveschaefer** [comment]
@netsafe Very minor question - should there be spaces in this string before the ( and after the comma?

Like this:
<!ENTITY invalidCertificateExceptions "Исключения Неверного (Недействительного, Ошибочного) Сертификата">

I'll leave it as-is for now, but we can add that if you like.

**Comment by daveschaefer** [comment]
Okay! I have cherrypicked the Russian translation and uploaded it as #164. It has been published! :) You can now download and build from source (there is a label for v4.6.1) or download and install directly from AMO here: https://addons.mozilla.org/firefox/downloads/file/319286/perspectives-4.6.1-sm+fx.xpi?src=devhub

I will send an email out to the list. Next I will work on merging the AMO fixes so we can get back to regular releases.

Thanks again for the translation! I appreciate it :)

**Comment by netsafe** [comment]
Hi @daveschaefer ! The brackets seem to be OK, actually. The only thing that I was forced to have a workaround for is the Wikipedia URL. It consists of non-ascii characters in url and I had to use google url shortener. The brackets are fine, I've checked it. Update about the built-in notaries : have you checked the default ones? They're actually responding, but it seems that they just don't run their cronjobs. How to reproduce it : pick a HTTPS site of your own, especially with self-signed certificate, check it with add-on regulary for a week and take a look at your webserver logs and notary replies.

**Comment by daveschaefer** [comment]
Thanks for the reply; sounds good. Yes I checked out the goo.gl URLs and they work nicely :)

Yes, I am well aware of the default notaries not responding :-/ It is a terrible issue and needs to be fixed ASAP. Since you have been kind enough to write code to fix the AMO blockers, however, I will merge those patches in first so we can once again deploy updated versions through addons.mozilla.org. Fixing the notaries requires several steps and I am still working through writing the code and working out details with Dan.

**Comment by netsafe** [comment]
Actually, they are responding, but not always AND - try the test with a self-signed certificate validation - it's not working. our link https://crowdcourse.net is the test I've perfomed. In the default doc the cronjob is supposed to run at 1 and 13 hours, but I'm running it every 4 hours, works better. As far as I can see, default notaries - maybe - don't run their cron jobs.

**Comment by daveschaefer** [comment]
Okay, I have merged in several other commits and changes and released those as v4.6.2. This clears up all-but-one of the AMO blocker bugs.

You can see the code as #165 . This fixes:

#103 
#160 
#161 
#162 

This has been uploaded to addons.mozilla.org for review.

I have purposely left the fix for #59 out for now. We can push it as its own release immediately afterward, to make testing easier and make sure everything works correctly.

Once again, many thanks to @netsafe for the code and patches! I have tried to credit you everywhere that I could; let me know if you want anything changed.

Thanks!

**Comment by netsafe** [comment]
Hi Dave! The AMO approval lags alot - still old version on addons website. Have it passed a code review? Are there any problems?

**Comment by daveschaefer** [comment]
Hi Alexey - I just checked and we are currently position 47 in the review queue. Yes, the main listing on AMO will unfortunately not update until we fix all of the amo_blocker bugs. That is why I really appreciate your work on fixing them. Thank you.

Once this release is through I will do another release (likely numbered 4.6.3) to move all of the Perspectives preferences to their proper location (again, using your patch), and *that* should finally fix everything. After that we should be able to use AMO for regular updates.

**Comment by netsafe** [comment]
OK Dave, I'll start pushing patches to both add-on and server as soon as it will be released

**Comment by netsafe** [comment]
Well, this "approoval queue" IS ridiculous, and it seems that I know why... By the same reason Convergence disappeared and by the diturbing fact I've recently discovered. The key milestones are : first-hand, an authorities can issue a must-accept one-side letter to conceal something, including a backdoor, and a second one is that if they'll need to change anything to enweaken the checking system - they will just sign a "patched" backdoored release and JUST publish it! There's no way to verify - on a client side - that add-on was not tampered from the code published by the developer. I.E. their signature and integrity IS verified, but the developer's ones ARE NOT, there's no such mechanism. I'm about to implement one =)

**Comment by daveschaefer** [comment]
Hey @netsafe , I'd be very interested to see what you come up with :)

I happened to still have the .xpi on my hard drive that I uploaded to AMO for v4.6.2. I calculated the hash as:

SHA-1: fe91a0c9b20c03a5723dafef76f563f3078827e0

This is the same hash I get from https://addons.mozilla.org/firefox/downloads/file/323232/perspectives-4.6.2-sm+fx.xpi

. I'm not sure if that assuages any of your concern :P

Strangely - if I clean and build the .xpi again I get a *different* checksum each time I build. I am not sure why but I'd like to look into it.

**Comment by netsafe** [comment]
The clean-and-rebuild procedure incorporates the build time into .xpi for sure, so that's why the checksum changes every time. The idea is, that there are some odious mechanisms like NSL [[https://en.wikipedia.org/wiki/National_security_letter]] and so on, and - the signature from the AMO and the integrity IS verified, but there's no author's one! It can be altered, re-signed by AMO and pushed out to replace a proper one - and an author will (probably) know about it from the issue tracker.

**Comment by netsafe** [comment]
by the way: [[https://addons.mozilla.org/en-US/firefox/addon/perspectives/]] is still "Perspectives 4.5.2.1-signed". When do they release a new build?

**Comment by daveschaefer** [comment]
So we are still one upload/release away from having the latest build displayed on the addons.mozilla.org site.

Originially AMO sent us a list of 'blocking issues' - these are the issues labeled with https://github.com/danwent/Perspectives/labels/blocks_amo_approval 

The most recent release and upload - v4.6.2 - fixes all but one of those. Thank you :) So we have submitted that for approval. Once we finally make it through the queue and get approved that is good, but the frontpage version of Perspectives still won't get updated - because we'll still have one blocking issue - the preference locations.

Thus, once we are approved I will finally be able to merge in your fix for the preference locations, and we can upload/release that as v4.6.3. Then that will also go through the approval queue, and finally once *that* is approved, it will show up on the front page again and everything will be back to normal (assuming they don't send any other violations :P)

Make sense?

**Comment by netsafe** [comment]
Yes, it makes one =) The one thing is disturbing - what takes them  SO long?

**Comment by netsafe** [comment]
so - what status it has got now? And take a look at my server code fork - it's working, but not all the features are implemented yet

**Comment by daveschaefer** [comment]
Okay, I finally got a reply and finished review from AMO - version 4.6.2 has been approved and posted to the site - https://addons.mozilla.org/en-US/firefox/addon/perspectives/versions/4.6.2 . Huzzah!

I am now merging in your commits that deal with preference migration. Thanks again for writing these.

These changes will require some thorough testing to make sure everything works. I will send an email to the mailing list to ask for volunteers.

**Comment by netsafe** [comment]
It was tested in VirtualBox set-ups, no problems were found. Tests were conducted before pushing, so you can trust in this fix for sure

**Comment by daveschaefer** [comment]
Okay! PR #173 takes care of fixing the preference location! I cherrypicked and merged netsafe's other two commits and published it.

The changes have been uploaded to AMO and we are now waiting for review. Once they give us approval we should be back to normal publishing updates!

Thanks again Alexey for the work writing this code :) I appreciate it!

**Comment by daveschaefer** [comment]
Okay! Version 4.6.4 is now out! That takes care of the commits here :) Thank you very much!

**Pull request closed without merging**
